# Generated by Django 2.2.1 on 2019-05-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descriptions',
            new_name='description',
        ),
    ]
